main: me.iamguus.reporter.Main
name: Reporter
version: 1.0
commands:
  report:
    usage: /<command>
    description: Report a player with ease.
  viewreport:
    usage: /<command>
    description: View a report with ease.
  reports:
    usage: /<command>
    description: View all reports with ease.  
